services:
  specpilot:
    image: mintplexlabs/anythingllm
    container_name: specpilot
    cap_add:
      - SYS_ADMIN
    env_file:
      - .env
    volumes:
      - storage:${STORAGE_DIR}
    restart: always
    network_mode: host

volumes:
  storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./llm_storage
