version: '3.8'
services:
  specpilot:
    image: mintplexlabs/anythingllm
    container_name: specpilot
    ports:
    - "3001:3001"
    cap_add:
      - SYS_ADMIN
    env_file:
      - .env
    volumes:
      - storage:${STORAGE_DIR}
    restart: always

volumes:
  storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./llm_storage
